services:

  redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    env_file:
      - .env.docker

    volumes:
      - ./docker/db/init-user.sh:/docker-entrypoint-initdb.d/init-user.sh

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker