spring.application.name=user-service

server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379

spring.config.import=optional:file:.env.docker[.properties]

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
