#!/bin/bash

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER ${DB_USERNAME} WITH PASSWORD '${DB_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB}
TO ${DB_USERNAME};

GRANT USAGE, CREATE ON SCHEMA public
TO ${DB_USERNAME};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public
TO ${DB_USERNAME};

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public
TO ${DB_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO ${DB_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO ${DB_USERNAME};

EOSQL