CREATE USER user_service_app WITH PASSWORD 'app_password';

GRANT CONNECT ON DATABASE postgres TO user_service_app;

GRANT USAGE, CREATE ON SCHEMA public TO user_service_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_service_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_service_app;